-- =====================================================================
-- Performance em escala nacional: uma cadeia de auditoria POR ELEIÇÃO.
--
-- Medição (npm run bench:national -- 200 100 64): com 200 seções votando ao
-- mesmo tempo, a vazão ficava em ~320 eleitores/s, igual a uma eleição só.
-- Das conexões ativas no PostgreSQL, 6,5 em ~8 esperavam o advisory lock da
-- cadeia GLOBAL de auditoria; a máquina estava ociosa. Projeção para 156 mi
-- de eleitores: 134 h (uma eleição dura 9 h).
--
-- Agora cada eleição tem a própria cadeia e o próprio lock: seções diferentes
-- não esperam umas pelas outras.
--
-- Um log de auditoria NÃO pode ser reescrito (seria o próprio ataque que ele
-- detecta). Por isso o formato é VERSIONADO:
--   format 1: a cadeia global existente, intacta (chain_key = 'global'),
--             onde eleições antigas continuam registrando eventos;
--   format 2: uma cadeia por eleição (chain_key = id da eleição), para toda
--             eleição criada a partir de agora.
-- =====================================================================

ALTER TABLE "audit_events" RENAME COLUMN "seq" TO "id";
ALTER TABLE "audit_events" DROP CONSTRAINT "audit_events_seq_check";

ALTER TABLE "audit_events"
  ADD COLUMN "chain_key" TEXT,
  ADD COLUMN "seq" INTEGER,
  ADD COLUMN "format" SMALLINT;

-- Eventos existentes: cadeia global, formato 1, posição = o antigo seq global
-- (que era contíguo). Os hashes não mudam: o formato 1 usa exatamente esses dados.
-- O trigger append-only bloqueia até esta migration; ele é desligado SÓ para este
-- preenchimento, que não altera nenhum dado coberto pelos hashes. Depois da migration,
-- verifyAuditChain() confere que a cadeia continua íntegra.
ALTER TABLE "audit_events" DISABLE TRIGGER "audit_events_guard";
UPDATE "audit_events" SET "chain_key" = 'global', "seq" = "id", "format" = 1;
ALTER TABLE "audit_events" ENABLE TRIGGER "audit_events_guard";

ALTER TABLE "audit_events"
  ALTER COLUMN "chain_key" SET NOT NULL,
  ALTER COLUMN "seq" SET NOT NULL,
  ALTER COLUMN "format" SET NOT NULL,
  ADD CONSTRAINT "audit_events_seq_check" CHECK ("seq" >= 1),
  ADD CONSTRAINT "audit_events_format_check" CHECK (
       ("format" = 1 AND "chain_key" = 'global')
    OR ("format" = 2 AND "election_id" IS NOT NULL AND "chain_key" = "election_id"::text)
  );

CREATE UNIQUE INDEX "audit_events_chain_key_seq_key" ON "audit_events"("chain_key", "seq");

-- id global gerado pelo banco (só ordenação/paginação; não entra em hash nenhum).
ALTER TABLE "audit_events" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY;
SELECT setval(pg_get_serial_sequence('"audit_events"', 'id'), coalesce(max("id"), 0) + 1, false)
  FROM "audit_events";
GRANT USAGE ON SEQUENCE audit_events_id_seq TO "urna_app";

-- Encadeamento verificado no INSERT, agora por cadeia.
CREATE OR REPLACE FUNCTION "audit_events_guard"() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
  expected_previous bytea;
BEGIN
  IF TG_OP <> 'INSERT' THEN
    RAISE EXCEPTION 'audit_immutable: audit events cannot be updated or deleted'
      USING ERRCODE = 'UE010';
  END IF;

  IF NEW."seq" = 1 THEN
    expected_previous := '\x0000000000000000000000000000000000000000000000000000000000000000'::bytea;
  ELSE
    SELECT "event_hash" INTO expected_previous FROM "audit_events"
     WHERE "chain_key" = NEW."chain_key" AND "seq" = NEW."seq" - 1;
    IF expected_previous IS NULL THEN
      RAISE EXCEPTION 'audit_chain_broken: % seq % has no predecessor', NEW."chain_key", NEW."seq"
        USING ERRCODE = 'UE011';
    END IF;
  END IF;

  IF NEW."previous_hash" <> expected_previous THEN
    RAISE EXCEPTION 'audit_chain_broken: previous_hash of % seq % does not match', NEW."chain_key", NEW."seq"
      USING ERRCODE = 'UE011';
  END IF;

  RETURN NEW;
END;
$$;
